const pembacaSeeder = [
  {
    judul: "Tips membuat Brand Desain Lebih Baik dan Sukses di Tahun 2024",
    gambar: "./uploads/articel-picture-1.png",
    deskripsi: "Deskripsi 1",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 4,
    trending: true,
  },
  {
    judul:
      "Langkah-langkah membuat illustrasi beruang pada aplikasi Adobe Illustrator",
    gambar: "./uploads/articel-picture-2.png",
    deskripsi: "Deskripsi 2",
    tag: ["Tips", "Desain"],
    number_reader: 3,
    trending: false,
  },
  {
    judul: "Proses pembuatan Icon dan menjual Icon di Internet",
    gambar: "./uploads/articel-picture-3.png",
    deskripsi: "Deskripsi 3",
    tag: ["Bisnis", "Desain"],
    number_reader: 2,
    trending: false,
  },
  {
    judul: "Membuat Desain Aplikasi Mobile dengan Figma dan Adobe XD",
    gambar: "./uploads/articel-picture-4.png",
    deskripsi: "Deskripsi 4",
    tag: ["Bisnis", "Desain"],
    number_reader: 1,
    trending: false,
  },
  {
    judul:
      "Tahap Pembuatan Dashboard Admin Menggunakan Codeigniter 4 dan MYSQL",
    gambar: "./uploads/articel-picture-6.png",
    deskripsi: "Deskripsi 5",
    tag: ["Tips", "Teknologi"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-7.png",
    deskripsi: "Deskripsi 6",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-8.png",
    deskripsi: "Deskripsi 7",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-9.png",
    deskripsi: "Deskripsi 8",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-10.png",
    deskripsi: "Deskripsi 9",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-11.png",
    deskripsi: "Deskripsi 10",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-12.png",
    deskripsi: "Deskripsi 11",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-13.png",
    deskripsi: "Deskripsi 12",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
  {
    judul: "Cara menjadi KAYA dengan Digital Marketing dan SEO",
    gambar: "./uploads/articel-picture-14.png",
    deskripsi: "Deskripsi 13",
    tag: ["Tips", "Gaya Hidup"],
    number_reader: 0,
    trending: false,
  },
];

module.exports = { pembacaSeeder };
